### ISSUE TITLE
Haven crashs on nexus 4/7 with lineages 14.1

### ISSUE THREAD

**Issue by 1312BACA** [guardianproject/haven#105]
Hello,
I have one Nexus 4 smartphone and one Nexus 7 tablet (2012, WiFi only). Both run with LineageOS 14.1 (android 7.12).  After installing Haven on them an I start it, I can klick through the first pages of this start and configuration dialogue. Then, when the app should start, it crashes. Does it work on devices with LineageOS?

**Comment by n8fr8** [comment]
Have you tried the 0.1.0 beta 5 release? It should fix this.
