### ISSUE TITLE
Audio setup wheel - strange behaviour

### ISSUE THREAD

**Issue by licaon-kter** [guardianproject/haven#108]
It's called in the UI as "wheel", it animates like a wheel, but it behaves like a slider.

Either make it a slider or make it behave as a wheel: no matter which point I touch the current value is raised/lower, not changed based on position first.

**Comment by fat-tire** [comment]
I noticed this too.  Looks like it's using [this widget](https://github.com/milosmns/actual-number-picker).  I was going to change it to act more like a wheel, but I think just changing the text will make things a lot clearer.  So I'm doing that.  See pull request #118.
