### ISSUE TITLE
Camera and accelerometer detection do not work when the screen is off

### ISSUE THREAD

**Issue by rober1s** [guardianproject/haven#111]
The app will be great when it is done. However, camera motion events to not trigger when the screen is off. Needing to have the screen on in order to use the camera motion sensor kind of defeats the intent of having a surreptitious security device. The sound sensor works with the screen off, but the on-board accelerometer also does not.

Phone is a Oneplus One running Lineage 15 Oreo 8.0

**Comment by E3V3A** [comment]
Yep, a common problem also causing battery drain. Need to keep screen alive with a black/dark screen, or prevent device from going into sleep mode.

**Comment by n8fr8** [comment]
Just want to make a point that "surreptitious" isn't always our goal with Haven. The primary goal is to deter or disincentive intruders, and if they enter, to notify you of their presence. Just like many alarm systems advertise their presence with stickers, blinking lights and cameras, the idea that a space is "Protected by Haven" could be one way this is deployed or configured.

*That said* you are absolutely right in expecting Haven's sensors to work when the screen is off :) 

Working on that now!

**Comment by rober1s** [comment]
> That said you are absolutely right in expecting Haven's sensors to work when the screen is off :)

I *love* it when developers agree! :-)

*_That said,_* having a cell phone sitting there on a desk with a bright yellow background and the words HAVEN Active" will greatly diminish the likelihood of ever discovering any covert activity of interest.

Whether or not you like the use of "surreptitious" to describe what will undoubtedly be the main mode of use for Haven, that is nevertheless how it is mostly going to be used. 

That aside, I'm glad we agree that the screen should be off while Haven is doing its thing. :-)

**Comment by deviantollam** [comment]
FWIW, i'm testing ver 0.2.0 alpha3 and it does work for me when the screen is locked.

verified on:

* a rooted OnePlus3T 
* an unrooted and stock Nokia 3.1

**Comment by theGrower** [comment]
Camera not working using version 0.1.0-beta-3 on unlocked Galaxy S9+ running LineageOS once the screen goes off. Same results for both front and back cameras.
I have an older phone to try, but need to get a new battery first.

**Comment by n8fr8** [comment]
new beta posted: https://github.com/guardianproject/haven/releases/tag/0.2.0-beta-3

please test when you can, and re-open or file new issues.

**Comment by theGrower** [comment]
I totally forgot to comment again. I did try the newest beta and all is well. Thanks!
