### ISSUE TITLE
1)Microphone recorder 2) way to disable Haven remotely 

### ISSUE THREAD

**Issue by leonardoporpora** [guardianproject/haven#112]
The microphone recorder in my phone doesn’t work if there is no light in the room, but it should i think. Than I think there should be a way to disable Haven remotely cause if I enable it when I come back home I start reviving 20/25 messages and photo about me. I think there is the need to make possible to disable Haven from Tor. To disable Haven remotely there is the need of a password and maybe 2FA with google Authenticator or something else.

**Comment by fat-tire** [comment]
Just a thought but it would be cool if it integrated with something like https://ifttt.com/ so that it could turn on when you enter a geofenced area, your wifi connects/disconnects or whatever other trigger...

**Comment by E3V3A** [comment]
@leonardoporpora 
> The microphone recorder in my phone doesn’t work if there is no light in the room
That sound very strange!

I agree to think #89 would be the simplest way to solve your problem until Remote control become feasible.

**Comment by jpalczewski** [comment]
> Just a thought but it would be cool if it integrated with something like https://ifttt.com/
Maybe integration with home assistant - https://home-assistant.io/ would be a better idea - it's self-hosted and has many ways of detecting presence, automation abstraction( https://home-assistant.io/docs/automation/examples/ ) and lot more. The biggest con with it is rather unfriendly configuration experience - rather that configuring everything from webpage there's necessity of writing many yaml files. 
There's a suggestion on the ha site now: https://community.home-assistant.io/t/integration-with-haven-from-snowden/36816 - further information provided there are rather appreciated. 

On the other hand: maybe implementing something related with MQTT would make haven more open to other alternatives(domoticz/openhab).

**Comment by fat-tire** [comment]
Yeah-- I was thinking mqtt would be cool for publishing status and subscribing to collect instructions which might be triggered by events- I dont know too much about Home Assistant per se (I'll check it out) but  Openhab integrates well with mqtt and even influxdb/grafana for cool visualizations of activity haven might detect.

Apparently paho [runs](https://eclipse.org/paho/clients/android/) on Android.  I've only used it w/ python (and have had issues recently with mosquitto) but it could be promising as a simple way to trigger the "armed" vs "unarmed" state at least at first.  You could pretty much use any IFTTT trigger (get an email, leave a geofenced area, connect to wifi, etc.) to publish to an mqtt broker (your own or something like adafruit's) which haven could be subscribed to.

Dunno how much bloat this would add tho.

**Comment by leonardoporpora** [comment]
Yeah MQTT I think is the best thing to do as you said it fits well with OpenHab.
