### ISSUE TITLE
Hardware & Android OS Limits Haven. Should there be a Kickstarter for a new & enhanced Haven device/platform?

### ISSUE THREAD

**Issue by dazcode** [guardianproject/haven#116]
You have a lot more control with custom hardware, and I think that a kickstarter for a cheap, portable, dedicated security device would reach and or exceed its funding goals and do quite well in the market right now.

And if you controlled the hardware, in additional to the existing features of Haven, such as motion/audio activated security events, you could implement such features as a 'wireless bug sweeper' in order to detect hidden cameras that might be recording you. Hidden cameras are a huge problem right now! https://www.cbsnews.com/news/airbnb-guests-find-hidden-cameras/ .

Perhaps this is already in the works? :)

**Comment by E3V3A** [comment]
This idea totally defeats the purpose of being able to use any old phone. The project is FLOSS so you can make your own Kick starter based on this, and see how that goes.

**Comment by dazcode** [comment]
I think the current Android project is great, and I don't think it would defeat that at all. I think if Haven has a set of core functionality that is used by all devices, as well as a set of device specific plugins and features, then each device can be fully utilized, from android burners to pi devices or even drones. And updates to the core code and platform would benefit all devices. I think the current Android app offers the opportunity to build up that core platform functionality, which can then be extended to other device platforms. (I also want this on my laptop computer to make sure nobody messes with my computer when I leave my work area).

I may have gotten ahead of things bringing up all this stuff. As far as the kickstarter thing, I'm not a marketer but I hope something like this eventually comes about. On the other hand maybe I've been watching too much Shark Tank, and so for that reason, i'm out.

**Comment by rober1s** [comment]
Let's see: Andriod phones have microphones, cameras, accelerometers, a compass, radios, and wifi.

And you're suggesting a special-purpose device that would have microphones, cameras, accelerometers, a compass, radios, and wifi.

Let me think about that.

**Comment by dazcode** [comment]
robert1s: I'm not sure what point you are trying to make. Not every phone can be rooted, and access to the hardware is controlled by the Android OS, which means just because the hardware may be present doesn't mean you can use it in the manner you want to. There are quite a few limitations and constraints and not all can be worked around.

**Comment by rober1s** [comment]
Ok, I'll try to be more clear.

"Google today announced that there are now more than two billion monthly active Android devices in use around the world. By comparison, Apple announced it had surpassed 1 billion active iOS devices in January 2016, but it hasn't provided an updated count since then.May 17, 2017"

In contrast, there are zero (0, i.e. not even one) special purpose devices equipped with sufficient sensors (like those 3 billion smart phones already have) to run the Haven app.

As a side note: do you think a special-purpose device equipped with wifi, data carrier radios, gps radios, cameras, an accelerator sensor, a gyro sensor, and a compass could be built for less than a mass-produced cheap burner smartphone? I don't think so.

The point being that with a little work, the Haven app can be made to run as designed on a whole boatload of phones already out there.

And who said anything about rooted phones? Haven does not require root to run.

Also, since you keep bringing it up: what are all of these Android and IOS limitations which you contend are being imposed on the hardware in such a way that Haven will be prevented from working as designed?

**Comment by dazcode** [comment]
I know Haven doesn't require root, if it was designed for rooted phones that would solve quite a few issues, but yes would not reach as many phones.

I'm a little surpised you would file a bug like this: https://github.com/guardianproject/haven/issues/111 and then ask me to explain to you limitations of non rooted Android apps? I mean I don't have to tell you the issues you can scroll through them as they are reported here. 

If all Haven is going to be is to work on non-rooted Android/IOS phones then that's fine, but I could easily see it as a start of something bigger, for example why not put this on a drone which can patrol your property? Why not put this on your laptop/PC?

As far as a custom device the form factor is important as well as power management and better sensors, but yes, basically it could just be a rooted burner device with slightly modified hardware. Haven could do a lot more with that.

**Comment by rober1s** [comment]
It sounds like you are purposefully missing the point. But that's your choice.

As far as my bug report: there are software methods to keep the camera alive when the screen is blanked. A Haven developer could probably do it with just a few lines of code.

I've wasted enough time on this, the thread is yours.

**Comment by dazcode** [comment]
Look, I did sidestep your question by referring you to the bug list, and I apologize for that. Compiling an accurate list of limitations may take a bit of time, but I'll try to come up with a list and post it here for anyone who is interested.

**Comment by dazcode** [comment]
On second thought i'm not sure what I would accomplish by posting the current limitations, as that information would probably not be well received and would just detract from the project as it currently exists, which is not my intention. I was really curious to discuss some future possibilities for Haven, but seems like now might be too early for that, and its probably a discussion best initiated by a core Haven member like n8fr8.
