### ISSUE TITLE
Crash on Sony Xperia Z

### ISSUE THREAD

**Issue by bonaime** [guardianproject/haven#122]
Hello,

I have one Sony Xperia Z smartphone Android 5.1.1

After installing Haven 0.1.0-beta-3, I can click through the first pages of presentation dialogue. Then, the app should start but it crashes. 

I installed it through google play and also with F-Droid with same results

**Comment by fat-tire** [comment]
Some fixes are in the pipeline (see the pull requests) that may address this soon.  To be sure, if you are able to post a log of the crash, please do!

**Comment by bonaime** [comment]
Solved with  0.1.0-beta-4
