### ISSUE TITLE
Fails to run on Galaxy S5, Android 4.4.2

### ISSUE THREAD

**Issue by SeraphimRussia** [guardianproject/haven#124]
Greetings!  Tried twice to install Haven, but I get "We're sorry but Haven has stopped."  I cannot get anywhere... Anyone else having such a problem, and / or know the way out?

Phone Model: SM-G900H
Baseband: G900HXXU1ANCI
Kernel Version: 3.10.9-1183700
dpi@SWDD5607 #1 
Mon Mar 31 14:25:05 KST 2014

Thanks!

**Comment by fat-tire** [comment]
Probably the missing resource error addressed in #67 but would need to see a log of the crash to be sure.

**Comment by n8fr8** [comment]
@SeraphimRussia any news? Did the latest update work for you?

**Comment by geraldkrug** [comment]
I made run on 4.4
