### ISSUE TITLE
Change support for React Native (More precisely Expo.io)

### ISSUE THREAD

**Issue by MichelDiz** [guardianproject/haven#125]
There is a very large demand from developers learning and already developing strong applications with React Native. Adopting RN for the project may have greater adoption of this JavaScript audience.

Not to mention that layout would be much more dynamic and we can use any set of existing libs for JS. With access to multiple APIs. UX or "themes" could be applied easely.

Native developing could continues the same if you do not wish to use Expo.io. just keep with React Native itself. There is also the possibility of using the same code for the IOS (Apple) system. And who knows extend the code to electronjs.org

Cheers

**Comment by bernaferrari** [comment]
I don't think it would provide the versatility this project needs, there are a lot of low-level stuff that RN wouldn't be able to provide or would be too much work to implement, plus would it be a complete rewrite.

**Comment by MichelDiz** [comment]
As I said, you could continue to use a native Android module within the React Native project. Faced with this fact I do not see why not adopt it.

**Comment by n8fr8** [comment]
RN comes up a lot, but isn't something the core team at Guardian Project has a ton of experience in. If there is a volunteer who wants to re-implement the UI layer in RN, and can show it is more sustainable and flexible, then possibly. 

At this point in time, this isn't a high priority.

**Comment by fat-tire** [comment]
I don't quite get the utility of doing this.  Styles and themes are already [available](https://developer.android.com/guide/topics/ui/look-and-feel/themes.html) within the Android framework, and the current UI works as far as I can tell.  What would be the advantage of a whole 2nd UI?  There are no plans to create an iOS port from this source, right?  (the "guts" having to do with the sensors, etc are all dependent on the Android framework).  But if it doesn't break anything, I wouldn't be opposed (not that my opinion really matters here..)

**Comment by MichelDiz** [comment]
I thought it would increase the base of support for creating new solutions or improving those that are already in action. And at the same time having a facility using a wide range of libs available. I thought this had some value. Crowd could worth something, but okay. Whatever. Stick in the course.
