### ISSUE TITLE
Microphone doesn’t work. 

### ISSUE THREAD

**Issue by leonardoporpora** [guardianproject/haven#135]
Microphone doesn’t work on my phone I never received registration even when it was activated and I was playing guitar.

**Comment by n8fr8** [comment]
When you open the microphone configuration screen, do you see the sound waves in the graph?

If not, do you have another app running that might be interfering with the microphone?

**Comment by leonardoporpora** [comment]
I do not see sound waves and I don’t have any program that should interfer with the microphone because the phone in new and I installed Only Haven, Orbot, Orfox

**Comment by fat-tire** [comment]
Question-- what is the phone/tablet hardware as well as the version of Android running?  (you can find the phone version in settings->Abut this Phone/Tablet -- Does the microphone work w/ other things like phone calls or say apps that record your voice?

Also, if you're able to get a log with logcat-- do you notice any kind of audio-related errors when you try to use the mic?

**Comment by leonardoporpora** [comment]
Yes it work I tried to make a signal call and it works I checked for the permissions and it has got permissions. It’s a Samsung Galaxy J3 (2016) Version of Android 5.1.1 Kernel version 3.10.65-12057946

**Comment by fat-tire** [comment]
And any errors appear in the log?  You could use the `logcat` command or something like [catlog](https://play.google.com/store/apps/details?id=com.nolanlawson.logcat) might show an error or warning involving audio or the microphone specifically.  If you could post any such items here or (if it's long) using [https://gist.github.com](https://gist.github.com) you could then link to the log directly.

**Comment by n8fr8** [comment]
This commit may address the issue 51186eba3b66e6d4acc5848fa3e63bb0ea0def9d 

The microphone configuration setting wasn't being saved, depending on how you were exiting the screen.

**Comment by leonardoporpora** [comment]
I will test it today 👍

**Comment by leonardoporpora** [comment]
I confirm that this issue is now fixed
