### ISSUE TITLE
Continue send me photo even if disabled

### ISSUE THREAD

**Issue by leonardoporpora** [guardianproject/haven#137]
Haven continue send me photo even if disabled. It’s really a problem. 
![image](https://user-images.githubusercontent.com/34192761/34390801-494c5fda-eb42-11e7-9ac5-8815928dc8f0.jpg)

**Comment by leonardoporpora** [comment]
A scuola you can see there is written start now but the camera was triggered and I received that photo.

**Comment by n8fr8** [comment]
Seems like the service is still active in the background, even though the user interface doesn't show it.

**Comment by leonardoporpora** [comment]
Yes is how I thought.

**Comment by leonardoporpora** [comment]
@n8fr8 have you got any idea of how can we fix it. It’s very very noisy to continue receiving photos even when it’s disabled

**Comment by n8fr8** [comment]
Definitely part of the next round of work. There is some disconnect between the UI and the service.

**Comment by leonardoporpora** [comment]
I confirm that this issue is fixed
