### ISSUE TITLE
Camera sensitivity in a sunny room

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/haven#146]
Reported on Twitter:

"Set up in a sunny room, Haven (@gethavenapp) generates a steady stream of false positives for movement as clouds pass by the sun. This is a significant problem to be addressed. Haven is currently not suitable for locations with natural lighting."

https://twitter.com/georgemaschke/status/945590775953416192/photo/1

**Comment by n8fr8** [comment]
"If alerts for detection of changes in ambient lighting (source of many true, but unuseful, positives with natural lighting) could be independently disabled, without also disabling motion detection, I think that would help greatly."

**Comment by sadsaddle** [comment]
I have code to fix this issue. New ti git & github. I have a local branch with the changes committed.  Unable to push or pull. How should I proceed?

**Comment by conorsch** [comment]
Hey there, @sadsaddle! Thanks for your interest. Try these guides for an explanation on opening pull requests to a repository you don't control:

* [Fork a Repo](https://help.github.com/articles/fork-a-repo/)
* [About pull requests](https://help.github.com/articles/about-pull-requests/)

Good luck!

**Comment by n8fr8** [comment]
This is a dup of #85 and we've got some work on this integrated already for the next beta
