### ISSUE TITLE
Update Settings screen to Material Design

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/haven#148]
Good advice here:
https://medium.com/@JakobUlbrich/building-a-settings-screen-for-android-part-1-5959aa49337c

**Comment by opticod** [comment]
@n8fr8, Can I work on this ?

**Comment by n8fr8** [comment]
Yes, please!

**Comment by Crdzbird** [comment]
I added some modifications to the function showTimeDelayDialog and added more functionality(optimization),
 can i be added to the work? 😄

**Comment by opticod** [comment]
For `TimeDelayDialog`, isn't it would be good to use Material design time picker as in #149

**Comment by percy-g2** [comment]
![screenshot_20171229-222937](https://user-images.githubusercontent.com/4012000/34442411-f3a65322-ece7-11e7-8604-3429c1ab5c70.png)

I have created the preference fragment according to current settings.

**Comment by opticod** [comment]
@percy-g2 I am already on it and have completed the layout and now working on its back end linking to new setting XML, will create the PR soon

**Comment by Crdzbird** [comment]
mmm... you have a point sir, well im gonna made that change 😃

**Comment by percy-g2** [comment]
@opticod cool. let me know if you need any help.

**Comment by opticod** [comment]
Sure. :smile:

**Comment by n8fr8** [comment]
I'm happy where we are with this now, with at least the Material look. I've also made some more improvements in my latest commit 37396bc1bec7c46dd15b07c7879ca3497a2ccc8e
