### ISSUE TITLE
Debug log

### ISSUE THREAD

**Issue by leonardoporpora** [guardianproject/haven#150]
We should start thinking about develop a Debug log to better understand all issues reported by Haven users. I think is one of the most important thing cause it will require time to developer and it’s true but later to understand an issue we will do much quicker

**Comment by fat-tire** [comment]
haven does do logging via logcat-- were you thinking of something like [Crashylitics](https://fabric.io/kits/android/crashlytics/summary)?

**Comment by leonardoporpora** [comment]
I was thinking something similar to Signal debug log. Crashylitics doesn’t seem to be so different to Signal Debug log

**Comment by E3V3A** [comment]
IMO and experience, 3rd party debug solutions like Leakcanary, Crashlytics etc. never, ever helped solve any bugs. It just took away and wasted a bunch of developer time, not to mention bloating the app. Just install a got logcat logger and tell people how to submit/file proper bug reports.
