### ISSUE TITLE
Some French translations don't fit in buttons

### ISSUE THREAD

**Issue by bonaime** [guardianproject/haven#156]
On Sony Xperia Z 1920 x 1080 with Haven 0.1.0-beta-4
![20171229_135520](https://user-images.githubusercontent.com/750709/34437665-995bdafa-eca0-11e7-8f53-0e63b6ff4036.jpg)
![20171229_135526](https://user-images.githubusercontent.com/750709/34437668-9adecc34-eca0-11e7-9c88-ba540bf5fc5f.jpg)

**Comment by fat-tire** [comment]
I think this may be the backslash strings thing fixed in #151.  Not a French speaker, but is the "S" from [this](https://github.com/guardianproject/haven/commit/4c0582dfa3fd560ed74906b2a8527da442cc87e0)?
