### ISSUE TITLE
MaterialDesignTimePicker Updated

### ISSUE THREAD

**Issue by Crdzbird** [guardianproject/haven#163]
Change the time picker in the MontorActivity with a Material Design, the hours are disabled due to timer setup.

![image](https://user-images.githubusercontent.com/7727498/34443813-41b56660-ec8f-11e7-9017-e60e2eeb0211.png)

**Comment by fat-tire** [comment]
So is this more of a "countdown" picker?  Here's a [material picker](https://github.com/wdullaer/MaterialDateTimePicker) for anyone wanting to do this.  It's apache licensed.

**Comment by tanvidadu** [comment]
I will like to work on this.

**Comment by opticod** [comment]
I have a PR https://github.com/guardianproject/haven/pull/149 targeted for this, which uses the same picker as mentioned above by @fat-tire

**Comment by n8fr8** [comment]
Merged, thanks!
