### ISSUE TITLE
Recording video on camera motion

### ISSUE THREAD

**Issue by rodrigocipriani** [guardianproject/haven#164]
It´s possible to record a video when there some motion on camera?

if it´s not, there some plans to implement that?

Thanks

**Comment by n8fr8** [comment]
Definitely possible and interest in video support. There is the idea of triggering video from the camera motion detection itself, but also perhaps triggering video from sound or other sensors, as well.

**Comment by Crdzbird** [comment]
Also maybe can be possible to gave the user the options of video quality and the format that they desire to save. I can work in that if you want? 😃

**Comment by rodrigocipriani** [comment]
Great Crdzbird! It would be great if you could do it.

Some another features that I think:
- Start record with a remote command
- Streaming without recording
- Save Small gif of record
- Change video recording quality (like you said)

**Comment by n8fr8** [comment]
We have to be very careful with any kind of remote command or control.

Let's just focus on video support as we have audio support now, without getting into more sensitive features of remote and streaming.

**Comment by leonardoporpora** [comment]
Yes I agree with @n8fr8 we must be very careful with remote controls. I think that now Haven has got other priorities.

**Comment by rodrigocipriani** [comment]
That's only suggestions, but I agree, in the first, videos can be like audios records are now.

**Comment by leonardoporpora** [comment]
Yes I agree too that video support is important and a cool feature but I think also that the user should decide to enable video recording or just audio and photo.

**Comment by rodrigocipriani** [comment]
Great idea leonardoporpora

**Comment by Crdzbird** [comment]
That's an excellent proposal, question... How it can be better to storage the video? In a SQLite table with the route to the file or save it as a byte array? Also the same question  for the gif

**Comment by Crdzbird** [comment]
Or if you wanna I leave it with both options

**Comment by leonardoporpora** [comment]
Yes both options is better

**Comment by percy-g2** [comment]
https://github.com/percy-g2/haven/blob/dev/src/main/java/org/havenapp/main/sensors/motion/Preview.java

i have got the video recording and saving working ( its totally a basic test) which captures 5 secs every time something motion change is detected.

**Comment by n8fr8** [comment]
This is now implemented, see #220
