### ISSUE TITLE
orbot stops whenever I try to enable remote access

### ISSUE THREAD

**Issue by twoprops** [guardianproject/haven#175]
Whenever I try to check the "Enable remote access via Tor Onion Service" box, Orbot opens, I get the "An app wants to open hidden server port 8888 to the Tor network. This is safe if you trust the app." message. When I click allow, I get the "Orbot has stopped" system message. Every. Time.

It doesn't matter if Orbot was running or not before attempting to open the hidden service.

This is on a Nexus 6 that I got directly from Google, running dead-stock Android 7.1.1. Orbot is up-to-date (15.5.0-RC-1-multi-SDK23) and Haven is the latest (29December2017) beta in the Google store. I've tried uninstalling and re-installing Haven and, of course, turnin'-it-off-and-back-on-again. Repeated tries just repeatedly crash Orbot.

Oddly, nobody else seems to have reported even a vaguely similar problem, yet it renders Haven useless and it's hard to conceive of a more standard Android environment.

Any ideas?

**Comment by christopher-owen** [comment]
Exact same issue here running on a Samsung Note GT-N7000 with Android 4.1.2. 
Haven 0.1.0-beta-3
Orbot 15.5.0-RC-1-multi-SDK16

**Comment by MTRNord** [comment]
Happens with one plus one too. Orbot is installed from The play store

**Comment by kushaldas** [comment]
Same problem if I install Orbot form the play store. I had to install Orbot `15.5.1-RC-2-multi-SDK23` from the F-Droid store. That worked. My `Haven` is also a nightly build.

**Comment by christopher-owen** [comment]
Removed the Playstore version of Orbot and installed the Fdroid version and it works fine.

**Comment by n8fr8** [comment]
Hmmm.... thanks for the reports. I thought the F-Droid and Play Store versions where the same, but maybe we forgot to push RC2 to Google Play? Or maybe not everyone is receiving it. Will double check today.

**Comment by twoprops** [comment]
I don't know much about the internal workings of the Play Store. It wasn't telling me that there was an update to Orfox, but I tried uninstalling it a re-downloading it just because. It's still reporting that it's at RC-1.

**Comment by lukeswitz** [comment]
Confirmed same bug Nexus 4 Play Store Orfox remains at RC1. F-Droid serves up RC2 properly and fixes this onboarding issue.

**Comment by n8fr8** [comment]
Orbot v16 should address this, and is out/available everywhere

**Comment by twoprops** [comment]
Working great! Thanks for what you've done.
