### ISSUE TITLE
Alarms dismissed

### ISSUE THREAD

**Issue by indiglofae** [guardianproject/haven#180]
Have there been any issues with this app dismissing Android alarms? My alarms were all dismissed this morning. This is the only new app on my phone. How can I resolve that without deleting the app if it is what caused this? Thanks

**Comment by n8fr8** [comment]
We don't touch any alarms. Could the issue be related to the calendar rolling over to 1/1/2018?

**Comment by indiglofae** [comment]
I think that was it. The alarm worked fine the next day. Thank you
