### ISSUE TITLE
Ensure dependencies are up-to-date

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/haven#184]
The Fresco library includes an out of date version of libjpeg-turbo (1.5) 
https://github.com/facebook/fresco/tree/master/imagepipeline/src/main/jni

There is a newer version that fixes CVEs documented here: https://www.cvedetails.com/product/22813/D.r.commander-Libjpeg-turbo.html?vendor_id=12120

However, we may not be vulnerable to the attacks as documented, based on the way Haven uses the library.

Regardless, we should audit all third party libraries, and consider forking and updating as necessary.

**Comment by mig5** [comment]
Somewhat related, I continue to also have trouble with derlio/waveform returning a 401 Authorization header from jitpack.io when I try to build Gradle in Android Studio (completely prevents me from compiling), wonder if anyone else reproduces with a fresh clone of Haven repo + fresh Android Studio 3.0 install

https://jitpack.io/com/github/derlio/waveform/library/1.0.3/library-1.0.3.pom

**Comment by BaranMichal25** [comment]
Rather nothing big, but we could start by installing security tools from GitHub marketplace eg. Snyk -
 [https://github.com/marketplace/snyk](url), which is free to use for open-source projects.
