### ISSUE TITLE
Onion Hidden Service not working (beta6)

### ISSUE THREAD

**Issue by mig5** [guardianproject/haven#185]
There is some sort of regression in the Tor web service since 0.1.0-beta-6 (I did a fresh install, not an upgrade)

I can toggle 'Remote Access', and get the usual Orbot prompt to allow a new hidden service on port 8888.

I can see the Haven web server listening on localhost:8888

However, after starting Haven, I don't get any Onion Service URL in my notifications in Signal.

Also if I click 'Service Address', I don't see the Onion Service URL, it's an empty string with cursor blinking.

Maybe something has changed in the new Material Design settings interface that means the Onion Service URL does not actually get stored?

It is working perfectly in beta5.

**Comment by n8fr8** [comment]
Hmmm, not seeing the issue here. I had a pre-configured onion service before the material design changes, and it transfered over fine with the new look. Will do some new testing from a clean install.

**Comment by mig5** [comment]
I will also test a standard upgrade from beta5 to beta6 to see if that sticks as expected.

**Comment by mig5** [comment]
I confirm that an upgrade from beta5 to beta6 retains the Onion address as expected, but for me an uninstall+fresh install of beta6 on the same device results in it not sticking after confirming the port 8888 in Orbot.

**Comment by n8fr8** [comment]
So it is an issue handling the intent launch result. Thanks!

**Comment by n8fr8** [comment]
Confirmed that the onion setup and permissions launches started in the new SettingsFragment weren't being passed back from the parent Activity

**Comment by mig5** [comment]
Confirmed fixed in beta7, thanks!
