### ISSUE TITLE
Device compatibility: Digiland DL8006 Tablet

### ISSUE THREAD

**Issue by gojomo** [guardianproject/haven#186]
The [Digiland DL8006](http://www.digi-land.net/En/Photo_Show.asp?InfoId=513&ClassId=44&Topid=43) is a cheap Android tablet available for ~USD$50, competing with the low-end Amazon Fire Tablets. It runs Android 7.0 and seems to have most/all of the sensors required for Haven. (It's definitely got two cameras and a microphone, and detects screen-orientation. It may not have an ambient light-level sensor.)

However, attempting to install 'Haven: Keep Watch (BETA)' from the Play Store shows a "Your device is not compatible with this version" message. 

Is this a temporary or permanent limitation? What changes would be necessary for it to be supported?

**Comment by n8fr8** [comment]
We may need to mark the SMS/telephony features as optional, so that devices w/o basebands can be supported.

**Comment by geraldkrug** [comment]
Android 4.4 works best

**Comment by gojomo** [comment]
@geraldkrug There is no practical option for average users to downgrade the DL8006 to an older Android, and if the app is still flagging certain device features (like telephony) as required, it is unlikely a downgrade would achieve compatibility. Further, it seems unwise to move to an OS near the end of its supported life. (The Wikipedia article on Android supported versions suggests 4.x is already unsupported, but its cited link doesn't yet support that assertion.)

**Comment by n8fr8** [comment]
The app is no longer flagging telephony as required, at least in the source code. Our next public beta build should work on tablet, no-based devices.

**Comment by geraldkrug** [comment]
I got a sim for haven from http://hologram.io
It costs $10 
Installed in android 5.1  success it logs sms alerts from Haven on OS android 4.4.2 
Its carrier agnostic :)

**Comment by gojomo** [comment]
@geraldkrug The DL8006 doesn't take SIMs.

**Comment by n8fr8** [comment]
We have remove SMS as a feature/permission from the app, and made telephony features optional, as well as cameras, and other devices. This means it can run on more devices, such as tablets and chromebooks.

**Comment by geraldkrug** [comment]
http://boughtupcom.scriptmania.com/cgi/intra/intranetserverform.html 
This runs on any browser. login server in a server submit #2 first to see server wasent started. Then submit #1 and then #2 to see login url
