### ISSUE TITLE
Use numerical keypad for phone number fields (beta6)

### ISSUE THREAD

**Issue by mig5** [guardianproject/haven#187]
The 'Register' and 'Verify' Signal options in beta6 no longer default to a numerical keypad, but the default alpha-numeric keypad.

This is much less user-friendly than how it is in beta5, in terms of entering phone numbers.

As per #185 I suspect this is due to the new Material Design settings/preferences stuff.

**Comment by percy-g2** [comment]
i have addressed that issue here https://github.com/guardianproject/haven/pull/179
