### ISSUE TITLE
Two verify codes sent in beta6

### ISSUE THREAD

**Issue by mig5** [guardianproject/haven#188]
In beta6, I get two Verify codes sent from Signal when I click 'Verify Signal'.

The second arrives after I click 'Verify' after entering in the first code, making me wonder if the act of 'saving' the first verification triggers another registration.

This does not occur on beta5.

**Comment by n8fr8** [comment]
This has been fixed in 37396bc1bec7c46dd15b07c7879ca3497a2ccc8e

**Comment by mig5** [comment]
Confirmed fixed in beta7, thanks
