### ISSUE TITLE
Remote phone number save option says 'Register' (beta7)

### ISSUE THREAD

**Issue by mig5** [guardianproject/haven#192]
In beta 7, when adding a 'Remote' phone (where notifications will be received), the 'save' option is titled 'Register', in the same way that the 'local' phone says 'Register' to register this number with Signal.

This might lead to confusion/concern that somehow the app will 'Register' the remote number with Signal when of course it's already in use on the receiving phone, and likely is the more 'important' existing Signal registration.

Can it be modified to 'Save' for the Remote phone option?

Thanks also for more clearly defining Remote vs Local, that was going to be another suggestion from beta6 :)

**Comment by tytower** [comment]
I'd like more explanation of what the local number is as opposed to what the remote number is? The register bit has me confused and I had to come her to find out Signal might be involved .  The documentation I have found so far is poor . Intentionall so?
