### ISSUE TITLE
Web server password is ignored (beta7) on first run

### ISSUE THREAD

**Issue by mig5** [guardianproject/haven#193]
In beta7 (fresh install not upgrade) I am able to set a password for the web server, but I don't get presented with the login auth when I visit the Onion Service start the countdown (immediately after 'saving' settings).

If I close the app (thus closing the web server) and re-open (thus starting the web server again), I see the login auth screen.

It implies that the webserver should be rebooted when the Preferences/Settings are saved.
 
I think this relates to the fact that there's no explicit 'Save'  on the Preferences/Settings page now, which means that the save() (which runs app.stopServer() / app.startServer()) might not run? (just a theory)

I expect for point-release upgrades, this is not an issue since the password was already set.

**Comment by n8fr8** [comment]
We can detect if you change the password, and make the appropriate server updates.

**Comment by n8fr8** [comment]
As of this comment: 52f962750502584d229431a8ba2486600e5e42bf we now require a password
