### ISSUE TITLE
Camera false positives on Nexus 7 2013

### ISSUE THREAD

**Issue by devrandom** [guardianproject/haven#198]
Noise in the acquired picture results in false motion detection.  This happens with the front and back cameras.

BTW, is there a list of devices Haven was tested with?

**Comment by devrandom** [comment]
![haven-noise1](https://user-images.githubusercontent.com/107096/34623205-140817dc-f205-11e7-9d06-73e968a21eef.jpg)

**Comment by tytower** [comment]
And my Huewai LUA-L02

**Comment by n8fr8** [comment]
We've implemented a camera sensitivity slider. We should add a list of test devices, but here's a start:

Galaxy S5, S6, Nexus 5X, Nexus 7, Xiaomi RedMi Note, Pixel, Galaxy Tab 2

Tracking this now on issue #85 

Thanks @devrandom ! :)
