### ISSUE TITLE
Haven goes in standby 

### ISSUE THREAD

**Issue by leonardoporpora** [guardianproject/haven#201]
My phone is a Samsung Galaxy J3 (2016) Version of Android 5.1.1 Kernel version 3.10.65-12057946  Have you got any idea of how can we fix it is a really big problem cause if there is a false positive detected by Haven and then it goes in standby when thieves come in my room Haven won’t detect anything.
Ps. Battery optimization is disabled.

**Comment by rober1s** [comment]
I reported the same issue here:

[Camera stops working when screen blanks](https://github.com/guardianproject/haven/issues/162)

Either the developers don't see this as a problem, or don't yet have an idea how to fix it. This is unfortunate, because Haven is useless unless it can be made to work with the display off.

**Comment by leonardoporpora** [comment]
In my case is not when the display goes off whereas it works perfectly
until the first detection that could be a false positive than after the
first detection I’m not able to receive any other alert. If for example a
false detection is detected at 8:00 pm if something else happens at 8:15 pm
I don’t be alerted and that’s a huge problem cause Haven become useless.

**Comment by fat-tire** [comment]
So there is always one false detection then it stops detecting?  Are you sure the false detection is "false" in that there was no cause for it?

**Comment by leonardoporpora** [comment]
No there is no always a false detection. It was an example it could be also a true detection at 8:00 pm but if he comes back at 8:15 pm Haven doesn’t work any more.

**Comment by artificialsheep** [comment]
I have a similar problem, the phone goes into standby (lockscreen) mode and the camera stops working.  Other sensors (accel namely) continue to send messages over Signal.  I'm happy to provide additional debug if this is not an issue the developers are seeing.

**Comment by n8fr8** [comment]
Let's call this a dup of #111 and consolidate discussion there?

**Comment by leonardoporpora** [comment]
It’s not really the same thing that happens. In his phone it stops when the screen goes in standby in my case after a first detection it goes standby till I unblock my phone.

**Comment by n8fr8** [comment]
Ah I see. Well, test with the latest 108 release, as it has a number of improvements related to this.

**Comment by leonardoporpora** [comment]
Fixed! GJ

**Comment by rober1s** [comment]
Great! When will there be a new release? Beta 11 was 16 days ago.
