### ISSUE TITLE
Constant inaccurate motion alerts

### ISSUE THREAD

**Issue by RobK19** [guardianproject/haven#207]
Hello, I am Robert from [IPVM](https://ipvm.com/), I will be publishing a report on the Haven app and I would like some feedback on an issue with motion detection. No matter what I have the threshold set to the app will spam me with motion constant motion alerts, I've tried numerous times to calibrate the motion detection (even setting it as high as it goes) but it seems to just keep spamming motion alerts. Keeping the Haven app active for 10 minutes will net me ~800 motion alerts while being pointed at a wall. 

I am posting here to ensure accuracy of the report and to hopefully get some input on the issue. To clarify i am using an LG G6 with Android 7.0.

**Comment by n8fr8** [comment]
Thanks for your interest. I just want to point out that Haven is in early public beta, and may not be ready for your report.

That said, the issue of camera sensitivity is one we are working on. We are implementing a sensitivity adjustment user interface similar to the sound and accelerometer tuner, that allows you to tune for the sensitivity of your specific camera. What we have learned is that every device is very different, and in many cases, the older Android phones we have tested on, are much less sensitive than high-end devices like your LG G6.

That said, a shorter term fix, is to just make the granularity of our sensitivity settings larger, to account for the variety of devices.

What is the timeline for your report, and would you be interested/willing to wait for our next beta update?

**Comment by n8fr8** [comment]
We're now tracking this in ticket #85
