### ISSUE TITLE
support rich, secure remote notifications

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/haven#21]
- can we do this through pure client/apps code
- we might need to use a server with Signal-CLI

**Comment by n8fr8** [comment]
related to #20 which might be more viable

**Comment by n8fr8** [comment]
- We need to support some kind of rich media remote notification to show alert event photos, audio
- Can we just do email?
- XMPP+OMEMO supports attachments, secure data

**Comment by n8fr8** [comment]
This library looks good for background email sending: https://github.com/yesidlazaro/GmailBackground

**Comment by n8fr8** [comment]
I think that the Onion/HS is definitely the way to go here, but I do want to add the ability to sync via onion between two PhoneyPot apps. This isn't hard, and it means you can essentially "pair" two phoneypots, with one polling the other at a configurable interval, to synchronize any events that are detected. 

We will still support the onion web interface, as well, for accessing from Tor Browser Desktop, Onion Browser iOS, etc.

Also, will be adding a password-based auth mechanism for now, since Authenticated Onions aren't well supported yet on desktop or iOS browsers.

**Comment by mrphs** [comment]
In case it becomes useful and you probably know this, but there's this [TextSecure library and command line tool](https://github.com/janimo/textsecure) that [INTERLOCK](https://github.com/inversepath/interlock) uses to make a minimal Signal client.

**Comment by n8fr8** [comment]
Interesting - had not seen that! We are using a fork of signal-cli for now, and it seems to be working well.
