### ISSUE TITLE
Camera sensitivty needs to be adjustable

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/haven#212]
">    - I tested both front and back cameras and found that the using the back
>    camera would make motion detection too sensitive and spam me with
>    notifications."

This might be a dup of another ticket?

**Comment by tytower** [comment]
Me too set it up and get 285 pictures and a flat battery . Can't seem to stop it

**Comment by n8fr8** [comment]
Got it. Expect major improvements in the next beta due out this week.

**Comment by n8fr8** [comment]
Duplicate of #85
