### ISSUE TITLE
Camera images can be upside down

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/haven#214]
">    - Using the back camera would send the images to my phone upside down."

**Comment by lukeswitz** [comment]
This bugfix doesn't work on Nexus 4 and other tested headsets. Unless there is a good reason for avoiding the Camera2 API, it should check the hardware then use the proper version. Something like this: 
`CameraCharacteristics characteristics = manager.getCameraCharacteristics(cameraID); 
if (characteristics.get(CameraCharacteristics.INFO_SUPPORTED_HA‌​RDWARE_LEVEL) == CameraCharacteristics.INFO_SUPPORTED_HARDWARE_LEVEL_LEGACY).‌​..` 

If legacy then use the old API; simple and solves multiple camera issues on here. Thanks for the hard work and let me know if I can migrate to the Camera2 API.

**Comment by percy-g2** [comment]
I agree using camera2 api for supported hardware

**Comment by lukeswitz** [comment]
Confirmed your fix is working on nexus 4. Great work, was a permissions issue on my end.
