### ISSUE TITLE
Web server not working (0.1.0-beta8)

### ISSUE THREAD

**Issue by mig5** [guardianproject/haven#230]
In 0.1.0-beta8, the web server simply doesn't start.

Verified via Netstat App and there is no listener on 127.0.0.1:8888, and the Onion service is not reachable on its Onion url.

I rebooted the phone after configuring all settings and trying a few times, but it still doesn't start up either when Haven app is opened nor when the monitoring is started.

**Comment by n8fr8** [comment]
Do you have a password set? It is now required.

**Comment by n8fr8** [comment]
Actually, ugh... I see the issue. The password check was put in the wrong place. Will issue an update today.

**Comment by n8fr8** [comment]
Beta 9 posted... let me know if it resolves the issue for you.

**Comment by mig5** [comment]
@n8fr8 confirmed fixed in beta9 - thanks for the rapid response!
