### ISSUE TITLE
Camera doesn’t work anymore on new beta

### ISSUE THREAD

**Issue by leonardoporpora** [guardianproject/haven#231]
The camera doesn’t work anymore on the latest beta

![1d824f3b-bbc8-4bf7-9227-a1b34846d006](https://user-images.githubusercontent.com/34192761/35166685-0245dda0-fd53-11e7-88cd-318f4ec75fb8.jpeg)
![e7a0b2a3-b992-4226-9f59-adabbbda53a8](https://user-images.githubusercontent.com/34192761/35166686-0272ced2-fd53-11e7-8da2-81f8425fdbf1.jpeg)

**Comment by lukeswitz** [comment]
Try this first:

[ ] Press the gear icon for Settings menu
[ ] Select "Camera Sensitivity"
[ ] Adjust the slider to the right to set the tolerance and remove the constant detected surface changes.

Possible cause: Onboarding calibration skipped on install.

**Comment by leonardoporpora** [comment]
Yes it’s fixed
