### ISSUE TITLE
This is a bit pie in the sky atm

### ISSUE THREAD

**Issue by tytower** [guardianproject/haven#237]
I've spent a few days experimenting with this . Someone has written a PDF presentation and plastered it all over the place but that blurb is about what might be possible **not what actually is possible atm.**

There are no working docs on this so you are on your own and it looks like it works in different ways on different brand phones .

The slider for camera sensitivity was definitely needed to stop repeated triggering but even now that is not enough and haven turns itself on and off and moves camera from back to front  and a load of other problems. The sound sensor seems to be the only one that can be set and actually work so far.

* One star for a good idea so far and another for some initial work done thereon.

**Comment by tytower** [comment]
2 months on and nothing has changed . Looks like the developer has given up and gone on to other things

**Comment by n8fr8** [comment]
Please stop with the unhelpful commentary. If you monitor the Github project, you'll see there has been continued development and integration of improvements from the community. If you look at out track record at Guardian Project, you'll see we've been involved in constantly improving and updating our apps for nearly a decade.

If you would like to have the latest and greatest features, you can subscribe to the nightly repository. There is information on how to do that on the website or github repo.
