### ISSUE TITLE
Crash on camera switch during active session

### ISSUE THREAD

**Issue by lukeswitz** [guardianproject/haven#238]
Version: 0.1.0-beta-10 
Device: Samsung Nexus 4 
Android Version: 5.1.1

- [x] Reinstalled from F-Droid & rebooted
- [x] Recreated w/following steps:
*  Press switch camera button on any active session. 

Possible cause: flags to stay awake and wakelock redundancies.

**Comment by n8fr8** [comment]
Ah good find! This is related to the fact that we no longer close the camera automatically when the surfaceview is destroyed. We have to manually stop it first... fixing now.

**Comment by n8fr8** [comment]
beta 11 should fix this

**Comment by lukeswitz** [comment]
Fixed: Tested on beta 11 from f-droid repo without issue 👍 
Thanks, you’re a beast on these nightly builds! Smoothest running session to date.
