### ISSUE TITLE
Takes one photo in lot of time

### ISSUE THREAD

**Issue by leonardoporpora** [guardianproject/haven#244]
I have tested Haven and before I
Got plenty of photos when haven detected movements instead rn I get only one photo in 1/2 minutes of movements. Example I play the guitar in front of haven camera I get only one photo and I’m jumping and moving my sled a lot... instead microphone sends me much more alerts

**Comment by lukeswitz** [comment]
Possibly related to the settings referenced in issue #232. Check that first, cheers.

**Comment by leonardoporpora** [comment]
No is not the same because now I don’t even get logs on the phone. I get one photo as log and photo is being sent to me. But the problem is that should has not be taken only one photo but much more. Before I have never had this problem

**Comment by lukeswitz** [comment]
Sounds like you have adjusted your sensitivity of the camera. Adjust that value so you see the desired yellow detection on screen.

**Comment by leonardoporpora** [comment]
Yes ok now I got more photos but not as many as saved in the log. I have the other issue open so I’ll close this :) thx man
