### ISSUE TITLE
Issues with fdroidserver depends?

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/haven#267]
From the travis-ci error log...

: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Failed to fetch http://ppa.launchpad.net/fdroid/fdroidserver/ubuntu/pool/main/p/python-typing/python3-typing_3.5.2.2-2~trusty_all.deb  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
E: Failed to fetch http://ppa.launchpad.net/fdroid/fdroidserver/ubuntu/pool/main/r/ruamel.yaml/python3-ruamel.yaml_0.13.4-2~trusty_amd64.deb  Unable to connect to ppa.launchpad.net:http:
E: Failed to fetch http://ppa.launchpad.net/fdroid/fdroidserver/ubuntu/pool/main/p/python-vagrant/python3-vagrant_0.5.15-1~trusty_all.deb  Unable to connect to ppa.launchpad.net:http:
E: Failed to fetch http://ppa.launchpad.net/fdroid/fdroidserver/ubuntu/pool/main/f/fdroidserver/fdroidserver_1.0.0-1~trusty1_all.deb  Unable to connect to ppa.launchpad.net:http:
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
apt-get.diagnostics
apt-get install failed
$ cat ~/apt-get-update.log
Ign:1 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty InRelease
Hit:2 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty-updates InRelease
Hit:3 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty-backports InRelease
Hit:4 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty Release
Hit:5 http://security.ubuntu.com/ubuntu trusty-security InRelease
Ign:6 http://toolbelt.heroku.com/ubuntu ./ InRelease
Hit:7 http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu trusty InRelease
Hit:9 https://dl.hhvm.com/ubuntu trusty InRelease
Hit:8 http://toolbelt.heroku.com/ubuntu ./ Release
Get:11 http://ppa.launchpad.net/fdroid/fdroidserver/ubuntu trusty InRelease [16.0 kB]
Hit:12 https://download.docker.com/linux/ubuntu trusty InRelease
Hit:14 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty InRelease
Hit:15 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty InRelease
Hit:16 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty InRelease
Hit:17 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease
Get:18 http://ppa.launchpad.net/fdroid/fdroidserver/ubuntu trusty/main amd64 Packages [8,153 B]
Get:19 http://ppa.launchpad.net/fdroid/fdroidserver/ubuntu trusty/main i386 Packages [8,163 B]
Get:20 http://ppa.launchpad.net/fdroid/fdroidserver/ubuntu trusty/main Translation-en [6,029 B]
Err:21 https://packagecloud.io/computology/apt-backport/ubuntu trusty InRelease
  Failed to connect to packagecloud-repositories.s3.dualstack.us-west-1.amazonaws.com port 443: Connection timed out
Hit:22 https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease
Fetched 38.3 kB in 6s (5,880 B/s)
Reading package lists...
W: Failed to fetch https://packagecloud.io/computology/apt-backport/ubuntu/dists/trusty/InRelease  Failed to connect to packagecloud-repositories.s3.dualstack.us-west-1.amazonaws.com port 443: Connection timed out
W: Some index files failed to download. They have been ignored, or old ones used instead.
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install fdroidserver openssh-client" failed and exited with 100 during .

**Comment by lukeswitz** [comment]
I've seen this before with travis builds; sometimes running a `sudo apt-get clean` before it kicks off the `addons` would resolve the artifact packages being held for f-droid as seen here: 
```
The following packages have unmet dependencies:
 fdroidserver : Depends: aapt but it is not installable
                Depends: zipalign but it is not installable
E: Unable to correct problems, you have held broken packages.
```
Hope that's of some help.
