### ISSUE TITLE
Signal: SSLPeerUnverifiedException using new build settings

### ISSUE THREAD

**Issue by lukeswitz** [guardianproject/haven#273]
After merging #269 the Signal functionality broke on both devices & simulators running 5.1-8.+. Attempting to register a local signal number, this is the response :

```
Request verify error: javax.net.ssl.SSLPeerUnverifiedException: Hostname textsecure-service.whispersystems.org not verified:
        certificate: sha256/HM+(removed for privacy) 
 DN: CN=textsecure-service.whispersystems.org,OU=Open Whisper Systems,O=Open Whisper Systems,ST=California,C=US
        subjectAltNames: []
```

I haven't gone through each dependency, so any help to reproduce this is appreciated. 

Thanks all,
Luke

**Comment by n8fr8** [comment]
It may be that we need to update the code for signal-cli-android https://github.com/guardianproject/signal-cli-android to keep up with the base project signal-cli: https://github.com/AsamK/signal-cli/commits/master

**Comment by lukeswitz** [comment]
Thanks, that's an issue for sure. I updated what I could before work and tested three approaches with the same problem over on this fork: https://github.com/lukeswitz/signal-cli-android. It's not an ISP or MITM issue; signal-cli-android broke in the merge of the last "updated build settings." 

A test beforehand would have been super helpful, as any following release without a fix won't include any Signal features. Please give it a test as the repo stands and report back when possible. Thanks

**Comment by lukeswitz** [comment]
Your branch is fine, it's the same idea as getting an insecure warning with a self-signed cert on a browser; appending an argument to the address works fine as does the Signal API.

- The Facebook & Picasso updates are not needed, requires a higher min SDK and causes the above issue. Things start to get weird but don't break using 1.8.0 & 2.5.2:
```
org.havenapp.main V/StudioProfiler: Transformed class: okhttp3/OkHttpClient
org.havenapp.main W/org.havenapp.main: Current dex file has more than one class in it. 
Calling RetransformClasses on this class might fail if no transformations are applied to it!
org.havenapp.main W/System.err: Request verify error: Bad response: 400 Bad Request
```
Proposing PR to fix this issue.

**Comment by lukeswitz** [comment]
Reopened for review of PR
