### ISSUE TITLE
Better explanation of heartbeat notifications

### ISSUE THREAD

**Issue by harlo** [guardianproject/haven#302]
Currently, users may only learn of deactivation or crash via heartbeat notifications. In testing, however, our group didn't quite understand the use case; I would recommend highlighting this feature and why it comes in handy in the wizard.

**Comment by n8fr8** [comment]
Perhaps the first heartbeat of a session could include an explanation message "Heartbeat activate: You will receive a short notification ever X minutes while Haven is still running"

We can also include a setting that uses <3 instead of Unicode, or allows people to configure the character entirely

**Comment by lukeswitz** [comment]
- User configurable message w/explanatory text to initial message, as @deviantollam and @n8fr8 suggested
- Appended device battery percentage to the alert

Concatenating strings for translation purposes downstream. Feedback very much welcome, PR on the way. Thanks!
