### ISSUE TITLE
Crash on startup Android 4.4.2

### ISSUE THREAD

**Issue by luciomarinelli** [guardianproject/haven#310]
Installed Haven 0.1.0 beta3 from F-droid repository on my old LG L65 smartphone running Android version 4.4.2. Haven crashes immediately at startup. Any suggestion?

**Comment by n8fr8** [comment]
Can you try the APK posted here:
https://github.com/guardianproject/haven/releases/tag/0.1.0-RC-1

This is the latest release candidate.

**Comment by luciomarinelli** [comment]
The latest release candidate no longer crashes on startup, thank you
