### ISSUE TITLE
Feature Request: ISO8601 ALL THE THINGS for date and time in logs  =)

### ISSUE THREAD

**Issue by deviantollam** [guardianproject/haven#335]
just a personal point of mine, and it ties in to feature requests like one i mentioned in #334 ... log entries and files saved on device would be best to have in ISO8601 format YYYY-MM-DD_HH-MM-SS so that they are immediately understandable by individuals of all cultures and (more importantly) the files can be correlated to one another if a user needs to reconstruct and assemble audio and video together.

**Comment by deviantollam** [comment]
just for detail, right now in the /phoneypot directory we have file names like...

153507598946.mp4
detected.original1535082691448.jpg
1535082734918.m4a

... and i can't tell the events to which these correspond.  in my perfect world, the files would have names like...

2018-08-23_23-50-23.jpg
2018-08-23_23-50-31.mp4
2018-08-23_23-50-31.m4a

(i mentioned this in #337 as well)

**Comment by archie94** [comment]
Since #312 we have separate folder with naming convention `YYYY-MM-DD_HH:MM:SS` corresponding to each events. We can apply this to file names too for clarity. :+1:

**Comment by deviantollam** [comment]
i see this now, yes, since i'm running 0.2.0-alpha4.  however, as stated in #348 the use of colons for directory names or file names causes problems when folk may wish to copy the files over from their device to a laptop or cloud-based backup solution.

instead of YYYY-MM-DD_HH:MM:SS i'd strongly recommend YYYY-MM-DD_HH-MM-SS (and i love the idea of both the individual files as well as the folders being given such names, that's awesome)

**Comment by fat-tire** [comment]
See if this got fixed by #351 -- note that straight up ISO8601 (or any filename that uses seconds as the smallest fraction of time) results in overwritten files... so I just added milliseconds to the end.

**Comment by archie94** [comment]
I believe this is fixed and can be closed.
