### ISSUE TITLE
Feature Request: index numbers for events in log entries

### ISSUE THREAD

**Issue by deviantollam** [guardianproject/haven#337]
let's say I have left Haven running and then when i deactivate it, there my log shows one entry, which had 20 detection events.

presently, that will appear in the log like this...

*Aug 23, 2018 23:50:31*
20 detection events

... well, as i have advocated for in #335, i'd love it if this main line in the Haven log were in ISO8601 format, but that's neither here nor there.  ;-)  let's talk about what we see if we drill down into the log by tapping because we want to see all these 20 events.

i'm then taken to a screen that can only show two (or two and a half) entries in the list at a time, because the preview image takes up significant screen real estate.  and as one scrolls through a series of Camera and Video detection captures, it's easy to become "lost" in this list.  "have i played that one already?  now i'm not sure" one thinks... because they all look more or less the same.  (each preview thumbnail tends to be the same neutral background image of the room)

Yes, each of these entries has a small date and time blurb just below the thumbnail (again, ISO8601 format would be so much better here in my view) but those all tend to blur together and are less helpful in a rapid scroll through the list.  

I'd love it if an indexing number of some sort were present.  The main log statement says I have 20 detection events?  Then once I drill down into this scrolling list of thumbnails, i'd love to see the numbers 01 through 20 in front of things like Motion (Video) and Motion (Camera)

again, related to #335, these entries do not correlate well to the filenames created in the /phoneypot directory.  Right now (and i'll likely duplicate this information in #335) we have file names like...

153507598946.mp4
detected.original1535082691448.jpg
1535082734918.m4a

... and i can't tell the events to which these correspond.  in my perfect world, the files would have names like...

2018-08-23_23-50-23.jpg
2018-08-23_23-50-31.mp4
2018-08-23_23-50-31.m4a

**Comment by n8fr8** [comment]
This is now part of the 0.2.0-beta-5 release, thanks to @archie94 
https://github.com/guardianproject/haven/releases/tag/0.2.0-beta-5-signed
