### ISSUE TITLE
Video playback not working on older devices

### ISSUE THREAD

**Issue by lukeswitz** [guardianproject/haven#342]
- Recorded .mp4 continues logging encoding instead of playing back. Possible it’s still parsing the frames together, even with 2 second recording duration. 

- Monitor does capture both image and video in logs without failure, a fix from prior builds, but the video does not respond to touch event. 

- Isolated to legacy devices AOS 5-7, flagship yet to be tested. 

- takes two attempts to remove the session log, sometimes won’t erase until fresh install.

**Comment by lukeswitz** [comment]
Log events could be related to #333

**Comment by n8fr8** [comment]
Yes, video needs a round of QA for sure on older devices.

**Comment by lukeswitz** [comment]
Now appears in logs as a blank video but the monitors all work otherwise, New log for issue:

` I/System.out: [WARN]	. (:0):	No frames output.`

**Comment by lukeswitz** [comment]
App doesn’t work on most older devices. Closing.

**Comment by n8fr8** [comment]
On Mon, Apr 22, 2019, at 8:37 AM, Luke Switzer wrote:
> App doesn’t work on most older devices. Closing.
> 

Video is definitely a feature I am happy to restrict to newer devices.

Beyond that, we should continue to try and support at least back to Android 6 and something like a Nexus 5 or Moto G.

Is the "most older devices" issue related to the camera performance? Turning off the live preview of motion would solve that.
