### ISSUE TITLE
very minor tweak:  /phoneypot sub-folders currently includ colon in folder names.  this can be a problem.

### ISSUE THREAD

**Issue by deviantollam** [guardianproject/haven#348]
i see that starting in 0.2.0-beta4 the entries in /phoneypot (or whatever folder the user has configured) get their own sub-folders for individual detection events.

the sub-folders are named YYYY-MM-DD_HH:MM:SS which is a nice touch... however, the use of colons means that it's problematic for users to, say, copy these folders over to a laptop since colons are sometimes disallowed by various operating systems.  using hyphens instead of colons would prevent this issue.

ideal scenario: the sub-folders in /phoneypot would be syntax'd as YYYY-MM-DD_HH-MM-SS

**Comment by archie94** [comment]
True! OS like Windows will prevent any folder name with colon. Will send a patch for this!

**Comment by fat-tire** [comment]
See if this got fixed by #351
