### ISSUE TITLE
Remove SMS support (thanks to Google!)

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/haven#364]
Due to changes in policy, we can no longer send SMS messages directly from Haven. We need to remove this functionality. 

https://play.google.com/about/privacy-security-deception/permissions/
https://proandroiddev.com/no-more-sms-call-log-permissions-now-what-9b8226de7827

We can still send Signal messages, and be remotely access via Tor/Onion.

**Comment by archie94** [comment]
Looking into this.

**Comment by E3V3A** [comment]
You need to request special permissions to send/receive SMS. Perhaps as a "seucrity" app?

**Comment by archie94** [comment]
> You need to request special permissions to send/receive SMS. Perhaps as a "seucrity" app?

This can be an option. Meanwhile preparing #369 just in case we do not qualify for the exception.

**Comment by lukeswitz** [comment]
Thoughts on submitting a permissions request form? Link takes you to Play Store portal for filing. Being open source and an alert based application should check all their boxes.

**Comment by n8fr8** [comment]
I submitted the time extension, and we received that. I then submitted the request for exception, and we were denied. It really doesn't make sense, since Haven *could* be set as the default SMS app on the device (since it is meant to be a second device).

I am going to see what I can do through our Google contacts, but honestly, I would rather focus on making the secure notification channels more easy to use, robust, etc. Working on both the Tor and a new Matrix.org integration option.

**Comment by lukeswitz** [comment]
Thanks for all that; sounds like Google went from 0-100 on their policies with the recent news on malicious app permissions. 

Score for security: SMS may have been simple, but it isn’t secure. Excited to work on the new web server and integration

**Comment by n8fr8** [comment]
"
#5: Is your app’s use of Call Log or SMS permissions to provide functionality required by law or regulation?
No

We reviewed your request and found that your app, Haven: Keep Watch (BETA), org.havenapp.main, does not qualify for use of the requested permissions for the following reasons:

The declared functionality {Default SMS} is determined to be unnecessary or not aligned with the core functionality of your app."

**Comment by n8fr8** [comment]
I realized I did request "Default SMS" since I thought we had to set the app to be the main SMS app in order to be allowed. However, we could try to request exception again with just SEND_SMS permission, since it is all that we use in fact. It is really confusing. Maybe I will try submitting the current build as a BETA and see what happens.

**Comment by lukeswitz** [comment]
That’s worth a shot. Maintains the feature and lets you pull it when the other side is done. 

Half those I introduce to the app outside the tech bubble don’t have working knowledge of Signal. After an explanation they love it; much the way Haven is an introduction to Signal & encryption for some. 

May you be victorious!

**Comment by n8fr8** [comment]
Okay, posted a signed build here: https://github.com/guardianproject/haven/releases/tag/0.2.0-beta-3
and submitted as beta to Google Play. 

Otherwise, @archie94 appreciate your work on this, as we may still need it! I was also thinking about supporting plugins for Haven, so we could implement, Signal, Matrix, Tor, SMS, Telegram, etc all as external APKs, you could install depending upon what kind of system you wanted to use. This would allow us to distribute the SMS feature through F-Droid for instance.

**Comment by n8fr8** [comment]
Ugh. Even with the reduced request for SEND_SMS only, we were denied.

"Thanks for contacting the Google Play team about your app Haven: Keep Watch (BETA), org.havenapp.main. We reviewed your app and found that it does not qualify for use of the requested permissions.

The declared functionality DEVICE_AUTOMATION is determined to be unnecessary or not aligned with the core functionality of your app."

I am going to escalate to Google contacts.

**Comment by paxperscientiam** [comment]
I've tried setting the remote notification number (SMS) to my Google voice number, but it didn't work. Is it related to this policy change?

**Comment by E3V3A** [comment]
I can confirm that the Gapps special permission application form is totally out-of-line confusing and intentionally (?) unclear. If someone has some google inside access, please try to clarify HTF you are supposed to understand these applications, if at all. Perhaps all applications just go to /dev/null and the auto replying *bot* doesn't GAF to what you say you need. 

I've also tried to apply for very similar permission for a number of apps, but without success. :-1:

**Comment by n8fr8** [comment]
We've removed SMS support from the main app. Exploring having a plugin or flavor build for users that really need it.

**Comment by DI555** [comment]
@n8fr8 , please do not drop good features like sms support and others !
Would suggest a special vanilla build placed here on github , and developing all possible good amazing features in this build!!!
But gp build will be with cut-off these functions... . Imo should be independing from what's there bigG think! ....;)

**Comment by E3V3A** [comment]
Yes, although on the one hand I'm constantly lecturing for not using SMS out of security concerns, but other hand, and in this case, it serves a very useful and basic function and at the end of the day, the fucking phones belong to **us** and not to Googles marketing team.

**Comment by oricou** [comment]
> We've removed SMS support from the main app. Exploring having a plugin or flavor build for users that really need it.

I do need this feature even if it means to install a free Android for a simple reason: sometime intruders cut electric wires which means no more Internet but SMS still works. They can also cut telecom wires,

And how Google dares forbide me to use some features on MY phone? I expected Apple to do such things, but not Google.
