### ISSUE TITLE
Camera configuration crashes in Settings

### ISSUE THREAD

**Issue by lukeswitz** [guardianproject/haven#376]
Workarounds:
 **ListViewActivity > SettingsActivty** - or -  **MonitorActivity > CameraConfigureActivity**, otherwise:
```
02-20 11:50:56.446 20738-20825/org.havenapp.main D/Camera: app passed NULL surface
02-20 11:50:59.611 20738-20825/org.havenapp.main W/CameraBase: An error occurred while connecting to camera: 1
02-20 11:50:59.611 20738-20825/org.havenapp.main E/Camera1: createCamera: Failed to connect. Maybe in use by another app?
02-20 11:50:59.613 20738-20825/org.havenapp.main E/CameraController: uncaughtException: Interrupting thread with state: STATE_STARTING due to CameraException: com.otaliastudios.cameraview.CameraException: java.lang.RuntimeException: Fail to connect to camera service
```

**Comment by lukeswitz** [comment]
Calling camera.stop before entering settings is a fix. Calibrate btn is disabled during session, should the same apply to the activity in settings? Would make sense.

**Comment by archie94** [comment]
> Calling camera.stop before entering settings is a fix. 

I think it would be best to bind the Camera to a `LifecycleOwner`. That would reduce these boilerplate code.

**Comment by archie94** [comment]
As far as I see, the current library we are using allows this.

**Comment by lukeswitz** [comment]
I’ll leave this to you. Cheers thanks.
