### ISSUE TITLE
Unable to erase the Logs

### ISSUE THREAD

**Issue by ingfabby** [guardianproject/haven#380]
Some devices do not allow the user to erase the logs

**Comment by archie94** [comment]
Hey, 
Which build are you on?

**Comment by archie94** [comment]
Also would be nice if you can provide details of the devices concerned and steps to reproduce (if any).

**Comment by n8fr8** [comment]
This is a support ticket issue from the old release on Google Play. This is fixed in the new work you have done.

I will be merging the SMS fix and shipping the update to the Play Store this week... I expect Google will accept it with the SMS removal.

**Comment by n8fr8** [comment]
@ingfabby please provide more detail on app and OS versions, device types, etc as you can in the future.

**Comment by ingfabby** [comment]
Hi,

Device: J5 Prime
OS: Android 6
Build: 0.1.0 R-C-1
