### ISSUE TITLE
Google Play app info outdated

### ISSUE THREAD

**Issue by lukeswitz** [guardianproject/haven#385]
Features & changelog are same as 2018 RC1. Listed dependencies are not accurate for attached build. 

Biggest issue is no SMS. Without any sort of onboarding to help the transition, users won’t know and assume it’s broken. Probably should put that in the app description. 

The intro screen still says “send you a text” aside from a pile of issues with signal. I suggest appealing the permissions with an addendum in the small comment box. I had the same code approved after a simple explanation was added instead of defending our code.

Let us know how we can help. Thanks

**Comment by n8fr8** [comment]
I tried to submit the app with the SMS features intact multiple times.

Any insight into the magic of why your explanation was sufficient to win the appeal?

**Comment by lukeswitz** [comment]
I was going to close this as it’s so early in the release and still beta it’s not a big deal. 

The magic, lots of cursing & fist shaking. First got rejected for automation. Submitted again, only change was adding more personal explanation for battery optimizations. Left the sms as is even though that was the permission originally in violation (no mention of battery optimization). I added a little bit, pandering to their policy in the comments box: Approved & confused. 

This wasn’t me alone, I’d say one of millions of devs caught in the new Google security by design mess sharing similar stories.
