### ISSUE TITLE
lineageos 16 nextbit robin crashing on motion detection

### ISSUE THREAD

**Issue by toxynoid** [guardianproject/haven#389]
I've installed lineageos from 31.03.2019 and haven beta 3. The subject says it all.

**Comment by n8fr8** [comment]
Detection meaning, when motion is detected or sound?

**Comment by toxynoid** [comment]
Haven crashes as soon as motion is detected.

**Comment by lukeswitz** [comment]
Does the camera app work okay on its own taking pics? If so try the following:

- install latest (04/01/2019) lineageos 16 nextbit robin nightly build 

- Delete/Reinstall Haven 

- Clear cached data for the Camera and Haven apps in device settings

Can’t be of more help without logs but looks to be recent camera changes in lineage causing this clash with Haven. 

Rolling back to an older build of lineage or trying the one from today is your best bet until Havens camera handling becomes more robust. 

Let me know how that works, thanks.

**Comment by toxynoid** [comment]
I updated Haven to latest beta - problem solved.
