### ISSUE TITLE
Overlay rendering too intensive 

### ISSUE THREAD

**Issue by lukeswitz** [guardianproject/haven#397]
Switching back to an overlay for motion detection has caused some problems. Memory leaks from cameraviewhandler and monitor activity combine to form a laggy, useless interface. Movement overlay appears once every ten second max until it crashes out. 

Archie supplied more logs than could ever be needed to track this down, seems the library was added using the readme setup which assumes a good camera on a new device. 

I’d vote to go back to the simple “xxxx detected” UX

**Comment by lukeswitz** [comment]
Seems the creation and rotation of the bitmap on frame processing causes this. The matrix rotation hangs the cameraView

**Comment by lukeswitz** [comment]
No use. Cart pushing horse.

**Comment by n8fr8** [comment]
Here is my proposal for overhauling the camera moving forward:

1) use hardware video mp4 recording on a loop. Records 30 second loops.

2) use preview frame to detect motion as we do now, but dont worry about rotation, matrix etc

3) if motion is detected, save the current video loop.

Seems like this approach will pop many balloons with one stone.
