### ISSUE TITLE
Review claims government responded to them

### ISSUE THREAD

**Issue by lukeswitz** [guardianproject/haven#402]
There’s bad reviews and then there’s this:

“ 	
Mar Bachmeier

May 27, 2019

ok this app is not bill snowdens i contacted developer email and got a 6diget complaint number for receipt (fedral trade commission and other government agency s use that and said my complaint will be sent to support department its icaan or nsa .”

?

**Comment by lukeswitz** [comment]
My question is, was anyone on the project contacted as this person states? Or is it just another angry user with a bad attitude and a case number?

**Comment by lukeswitz** [comment]
Also, make it bold: this is not bill Snowden’s app.

**Comment by n8fr8** [comment]
Good ol' Bill Snowden!

I don't even know what their complaint is. I will ask our support team if they saw any emails of this kind.

**Comment by n8fr8** [comment]
Yeah, we got an email from him claiming that since the camera is "not HD" we must be recording remotely. Nothing to see here, move along!

"Thank you for fast response ,I notice poor resolution and then I knew camera recording remotely camera through my camera no HD ."

**Comment by lukeswitz** [comment]
Thanks Nate, gave me a laugh anyhow
