### ISSUE TITLE
Events empty on remote device

### ISSUE THREAD

**Issue by zcar300** [guardianproject/haven#410]
I have just started trying to use Haven so I'm sorry if this is a dumb problem.

I have the haven app all setup on an old Pixel and it is recording events. When I view the event log on a remote device, Pixel 4 XL, using Tor browser, it says there are events but when I click on the log for the day I want to view there are no events shown. It is updating the number of events, so that's working. 

When I view the logs on the Haven device I can see the audio and video events. Although when I try to play any of the videos the app crashes. I can view pictures just fine.

**Comment by fat-tire** [comment]
I think this was an issue with the coordinatorlayout and constraintlayout and I just submitted what I think is a fix.  At least it doesn't crash any more.

**Comment by zcar300** [comment]
How do I make sure I'm on the latest build? I have fdroid set up, and it says my apps are up to date. The Haven app says it's v0.2.0-beta-5 (214). 

Videos still crash the app. And it seem to only record one or two seconds of video.

**Comment by hitchhooker** [comment]
I built new release out of latest github source code but problem seems to persist and without visible events remotely, this application barely has any purpose with notifications that cannot be watched. 
Can anybody point out me to right direction what could cause the bug of triggered events not being seen and has this option worked before?

**Comment by archie94** [comment]
Hmm this is really odd. If events are triggered there should be logs. @hitchhooker Do you think you will be able to debug if there are any error logs?
Do you think you can access `haven.db` and let me know if there are any entries corresponding to your events?

**Comment by hitchhooker** [comment]
So seems like pictures and audio are sent fine through Signal but when I enter to webserver 127.0.0.1:8888 I can see Events list right but clicking into 127.0.0.1:8888/event/6 shows only heading Event: Apr 14, 2020 15:46:56 without further content.

First time im building and running android application so not so familiar with debugging, but I will give a try.

**Comment by archie94** [comment]
Ah. Okay.

Are the logs visible on the device which triggered the event(s)?

**Comment by hitchhooker** [comment]
![Screenshot_20200414-160233](https://user-images.githubusercontent.com/15621959/79237873-f4fdd680-7e6e-11ea-9927-acf1c57ccfc0.jpg)
![Screenshot_20200414-160229](https://user-images.githubusercontent.com/15621959/79237875-f62f0380-7e6e-11ea-8e45-cdb8fae906b6.jpg)
![Screenshot_20200414-160211](https://user-images.githubusercontent.com/15621959/79237876-f62f0380-7e6e-11ea-8cab-32a4daf21f4e.jpg)
Yeap so database seems to be fine locally but nothing gets shown in webserver.

**Comment by archie94** [comment]
Thanks for debugging. Will get back as soon as I can.

**Comment by archie94** [comment]
Thanks for reporting this issue @zcar300 
@hitchhooker Thanks for the help in debugging. 
#416 has been raised which hopefully will solve this issue. It would be great if anyone can cross verify this by building from my branch. :) 

Thanks!

**Comment by hitchhooker** [comment]
Just built archie94:webserver_bug branch, tested on my pixel3 and webserver works supposedly. Thank you very much for spotting the bud and keeping to project up.

**Comment by santi6291** [comment]
Any chance will have this be released soon?

**Comment by n8fr8** [comment]
Reviewing now

**Comment by bruceleerabbit** [comment]
I just installed the latest release (0.2.0-RC-1) version code 2001, and this bug is still there.

I know this was not a problem on version 0.1.0-beta-3 (ver.code 102).  I would rather not run a version that old.  Does anyone know of a more recent version on the [releases page](https://github.com/guardianproject/haven/releases) that doesn't have this bug?

**Comment by archie94** [comment]
The fix has been merged to master but hasn't gone live in any release as of yet. Do you think you will be able to build from source?

Thanks!
