### ISSUE TITLE
Recording video Bug

### ISSUE THREAD

**Issue by zcar300** [guardianproject/haven#413]
When Haven senses motion it only records 1-3 seconds of video. I don't see any way to set the length of the video clips. They are also very low framerate. More like a time lapse than an actual video.

Version 0.2.0-Beta-5-signed (214) Fdroid says it's up to date.

**Comment by lukeswitz** [comment]
Duration can be changed under the video recording setting. Use the gear icon to get there. Frame rate is a work in progress...

**Comment by zcar300** [comment]
Is it the video monitoring length? That reads like an amount of time it will record video. Not how long the individual videos will be. 

Thank you.

**Comment by lukeswitz** [comment]
That sets the length of each video. Cheers & new build on the way

**Comment by zcar300** [comment]
Great, thank you.

**Comment by zcar300** [comment]
So I changed the "set video monitoring length" to 1 minute. It is now recording videos between 1 and 4 seconds long.

**Comment by lukeswitz** [comment]
> So I changed the "set video monitoring length" to 1 minute. It is now recording videos between 1 and 4 seconds long.

Confirmed, 04s is the longest duration of video I can get the app to pull on any device up to AOS 10. Is anyone capturing the set duration in their preferences? If so, what version of Android are you on? Please and thank you

**Comment by xloem** [comment]
@lukeswitz my phone seems to really struggle to encode the video, leaving things very choppy.  i notice the project currently uses jcodec which is pure-java: it sounds like you guys would like some help switching to an NDK solution to encoding?
