### ISSUE TITLE
screen orientation, and sensitivity of camera

### ISSUE THREAD

**Issue by Ljon4ik4** [guardianproject/haven#439]
Hi, 
(Sorry it this is the wrong place for such a bugreport!)
I installed Haven, my phone is set to lock in vertical orientation, but still the haven app switches to the horizontal one. This would not be a problem in itself, but it seems to break the camera sensitivity: When in landscape mode the camera sensor gets extremely insensitive (regardless of settings).

Haven version (today, fresh from the fdroid store), 0.2.0-RC-1.

Phone:
Aquarius U Plus 
Android 7.1.1

**Comment by lukeswitz** [comment]
Thank you for providing the device info, that’s very helpful in recreating the issue. I’ll look into it right away

**Comment by lukeswitz** [comment]
Got that squared away with an easy fix; resolved with PR #440 to respect device orientation 

![screenFix](https://user-images.githubusercontent.com/10099969/105640086-54930480-5e39-11eb-8447-a8073a2aaceb.png)

**Comment by Ljon4ik4** [comment]
Nice, Thanks a lot!
