### ISSUE TITLE
"Haven is active" notification on lock screen

### ISSUE THREAD

**Issue by micahflee** [guardianproject/haven#44]
When Haven is activated, it shows this notification on the lock screen.

![signal-2017-12-11-094354](https://user-images.githubusercontent.com/156128/33845336-f72daf8e-de57-11e7-9d30-d3ed96c893b5.png)

There should be at least an option to not show it there. If you're using Haven as a security device, like in a hotel room, and an attacker picks up the phone and looks at the lock screen, in many situations it would be better if they didn't realize their actions were being logged.

**Comment by cdeange** [comment]
On recent Android versions (especially Android 8.1), you're required to post a notification if your app is running in the background, so that users are aware of what apps are always running. You should be able to long-press the notification and tell the OS that you want to always hide Haven notifications – that might be the only foolproof way to do so. This shouldn't affect its ability to run in the background.

It wouldn't hurt to give those kinds of instructions in the app though, for users that do want to hide the notification.

**Comment by dsiddy** [comment]
@cdeange, do you happen to know if the Android folks published any documentation regarding the requirement that you cite? It seems like an excellent best practice, to be sure, but I'm having trouble tracking it down in the [changelogs](https://developer.android.com/about/index.html), and the virtual device that I'm using for testing (which runs Android API 27) doesn't seem to enforce it.

**Comment by n8fr8** [comment]
@micahflee this should be fixed now. Please test and let me know!

**Comment by leonardoporpora** [comment]
I have the same issue, In my phone there is the notification of Haven but there is written a sensor was triggered. @n8fr8

**Comment by cdeange** [comment]
@dsiddy sorry for the late reply, I found it in the documentation for [Service](https://developer.android.com/reference/android/app/Service.html#ProcessLifecycle):

> A started service can use the startForeground(int, Notification) API to put the service in a foreground state, where the system considers it to be something the user is actively aware of and thus not a candidate for killing when low on memory. (It is still theoretically possible for the service to be killed under extreme memory pressure from the current foreground application, but in practice this should not be a concern.)

**Comment by dsiddy** [comment]
No worries whatsoever, @cdeange. Thanks for taking the time to indulge my curiosity.

**Comment by n8fr8** [comment]
I believe this is fixed? Will close, but please re-open if testing of next beta release shows different.
