### ISSUE TITLE
Improve Signal activation

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/haven#51]
Setting up Signal notifications is hard. For instance, users might forget to add a country code "+1" to the numbers, and sometimes it is confusing which number goes where.

Make it better!

**Comment by n8fr8** [comment]
We should also support voice/landline verification

**Comment by joncamfield** [comment]
The "don't use your number" text is confusing; why can't I use the device's phone number? How can I get a different phone number to use?

**Comment by n8fr8** [comment]
We've made progress here with the latest release. More to come in future issues!
