### ISSUE TITLE
Make Haven localizable

### ISSUE THREAD

**Issue by facyber** [guardianproject/haven#61]
Would you consider making the Haven localizable? I think it would help many people who don't know very well English, but still want to use the app. 

Of course it would be completely voluntary.

**Comment by n8fr8** [comment]
It is already localized and translated into Spanish. I can provide the link to Transifex where we make it easy for you to provide translations.

**Comment by n8fr8** [comment]
You can provide translations here: https://www.transifex.com/guardianproject/haven/

**Comment by facyber** [comment]
Thanks for the link. I requested Serbian language, so I will get on localization soon as I can. :) 

Thanks!

**Comment by licaon-kter** [comment]
I've made a request on Transifex, hope you get a chance to approve it.

Also, since you've merged translations directly on Github, you might need to push these changes to Transifex too.
