### ISSUE TITLE
Signal notifications fail with "Authorization failed!"

### ISSUE THREAD

**Issue by temal-** [guardianproject/haven#72]
I did the following:

- Used a "new" phone (Android 7.1.2 - Lineage 14.1-20171220-NIGHTLY-hammerhead) without a SIM card
- Installed Signal
- Registered new number to signal and activated it via "call me instead of SMS"
- Verified that Signal is actually working by sending multiple messages
- Installed Haven
- Haven shows the correct number in `Current Signal Number`
- Pushed "SEND TEST MESSAGE" button
- See the following error via `adb logcat`:

```
12-23 11:17:13.257  5472  5472 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
12-23 11:17:15.997  5472  5472 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
12-23 11:17:16.869  5472  9679 W System.err: Failed to send message: Authorization failed!
```

**Comment by n8fr8** [comment]
The Signal setup is confusing, so you may have missed a step, or misunderstood.

First, get Signal running on the phone you want to receive notifications on. You can just setup Signal as normal here, using the device's phone number.

Second, on the Haven device, you don't need to install Signal. From within Haven's settings, look for the "Register" button, and tap on it. A dialog will open, in which you put the Signal number you want to send from. This can be a new virtual number, or it can be the devices actual number, if it has one. The main point is, once you register that number with Haven, you won't receive Signal messages in any Signal app you have configured to use it.

After you register, you should receive an SMS with the verification code. Tap the "VERIFY" button in Haven settings, and enter the code there.

Then try sending a test message using the button in Haven's settings.

Another tip is, to always enter phone numbers formatted with the full country code, +12125551212 etc
