### ISSUE TITLE
LICENSE: Free Software or Open Source?

### ISSUE THREAD

**Issue by IonicaBizau** [guardianproject/haven#83]
First of all, nice job! Keep up the great work! :rocket: :+1: :sparkles: 

---

Some may find it confusing that the LICENSE is GPL v3, but the README file mentions *open-source*.

From `README.md`:

> We are announcing Haven today, as an open-source project, along a public beta release of the app.

From `LICENSE`:

```
 GNU GENERAL PUBLIC LICENSE
                       Version 3, 29 June 2007
```

`@Snowden` used the term *open-source* in [this tweet](https://twitter.com/Snowden/status/944374775736041472), as well.

So, is it free software, open-source software or some combination (in that case, maybe the license has to be clearer)?

**Comment by fat-tire** [comment]
I'm guessing he means "open source" in the generally understood conversational way that the source code is available and development is an open process, not by the RMS-approved strict definition.

**Comment by n8fr8** [comment]
The use of the GPL license speaks for itself, no? At Guardian Project, we generally use the entire "Free, Libre, Open-Souce Software" (FLOSS), which is fairly commonly accepted and understood.
