### ISSUE TITLE
Downloading on Play Store, Haven app crashes on Docomo and S3 Galaxy

### ISSUE THREAD

**Issue by augbog** [guardianproject/haven#84]
I have a few Android devices and wanted to try Haven and all my phones crashed saying Unfortunately Haven has stopped working. Is this a known issue? I have submitted system logs on crash via Play Store but can also try to post logs when I have a chance.

**Comment by fat-tire** [comment]
I'm guessing this is related to a missing resource issue on older versions of Android that should be fixed son.

**Comment by fat-tire** [comment]
...fixed soon

**Comment by augbog** [comment]
@fat-tire thanks! That sounds accurate, I was looking at the logs and I do think I recall seeing something in Drawable.java that was throwing the error and missing resource was mentioned somewhere in the error. If this is a known issue, I can close this but otherwise, I can leave this open to help track the issue.

**Comment by n8fr8** [comment]
Thanks for the report, and testing. We'll test the PR fix, and if all is well, merge it and put out an update after Christmas.

**Comment by augbog** [comment]
Thanks @n8fr8! Merry Christmas :)

**Comment by derppppp** [comment]
Same issue on an LG VS870 running Android 4.1.2

**Comment by n8fr8** [comment]
Please try the latest release, and let us know if it works.

**Comment by augbog** [comment]
I confirmed the app works on S3 Galaxy -- still need to test my other device but I think this issue can be closed. Feel free to comment and reopen if you see the issue persist :) and thanks for the hard work guys!
